### ISSUE TITLE
[FEATURE REQUEST] Access to overwritten, real-time functions and elements

### ISSUE THREAD

**Issue by tungs** [tungs/timeweb#9]
**Is your feature request related to a problem? Please describe.**
In some cases, it's desirable to use real-time functions and elements instead of virtual time functions and elements. Currently the way to access the overwritten time-handling functions and code use undocumented, potentially changeable features.

**Describe the solution you'd like**
`timeweb` should explicity export these functions to the `timeweb` object in some way.

**Describe alternatives you've considered**
The current way of using undocumented features works, but isn't ideal.

### Tasks for this feature:
- [x] Figuring out export property name(s) for the old functions. ***Update**: It's `realtime`. For instance, `timeweb.realtime.setTimeout` versus `document._timeweb_oldSetTimeout`*.
- [x] Referencing or moving the old objects from those found in [overwrite-time](https://github.com/tungs/timeweb/blob/00fd6de9baea2dd4defac8a2027e50d57eabbc3e/src/overwrite-time.js#L11-L21) to those properties. If the prefixed `_timeweb_old` globals are removed, this could potentially create some breaking changes. ***Update**: They were removed as of v0.2.0.*
- [x] Those calling the old `document.createElement` and `document.createElementNS` should also add the property `node._timeweb_customized = true` when initializing the node and returning it, so it doesn't get processed by `timeweb`'s mutation observer. ***Update:** `element._timeweb_customized` is renamed/split into two properties `element._timeweb_processed` and `element._timeweb_realtime`, for when timeweb has already processed the element or whether it shouldn't be processed at all, respectively.*
- [x] (Potentially) Check for a custom attribute in HTML elements in case if the user doesn't want timeweb to overwrite it. Applicable in cases where raw HTML is used and added to the DOM. Maybe something like `data-timeweb-realtime`.

**Comment by tungs** [comment]
v0.1.2 added the previous functionality to be accessible via the `realtime` property. Most are the old functions bound to `window` or `document`, but some, like `timeweb.realtime.createElement` add properties like `element._timeweb_realtime` to them.

v0.2.0 removed the prefixed global variables (e.g `window._timeweb_oldSetTimeout`).

**Comment by tungs** [comment]
v0.2.2 introduced support for `data-timeweb-realtime` to skip processing certain elements.
